### ISSUE TITLE
Failed to build after upgrading to Flutter stable v 2.2.2: cannot find symbol VERSION_CODES.Q

### ISSUE THREAD

**Issue by aptarmy** [mannprerak2/nearby_connections#35]
Before I upgraded to the latest version of Flutter, there wasn't any errors while building the application.
After running `flutter upgrade` and then run `flutter run --verbose` I got the following error.

```
[        ] > Task :nearby_connections:generateDebugBuildConfig
[  +97 ms] > Task :permission_handler:generateDebugBuildConfig
[  +99 ms] > Task :permission_handler:javaPreCompileDebug
[ +900 ms] > Task :permission_handler:compileDebugJavaWithJavac
[        ] > Task :nearby_connections:javaPreCompileDebug
[ +599 ms] > Task :nearby_connections:compileDebugJavaWithJavac FAILED
[        ] > Task :permission_handler:bundleLibCompileDebug
[        ]
/home/apt/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/nearby_connections-3.1.0/android/src/main/java/com/pkmnapps/nearby_con
nections/NearbyConnectionsPlugin.java:448: error: cannot find symbol
[        ]                 if (VERSION.SDK_INT < VERSION_CODES.Q) {
[        ]                                                    ^
[        ]   symbol:   variable Q
[        ]   location: class VERSION_CODES
[        ] Note:
/home/apt/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/nearby_connections-3.1.0/android/src/main/java/com/pkmnapps/nearby_con
nections/NearbyConnectionsPlugin.java uses or overrides a deprecated API.
[        ] Note: Recompile with -Xlint:deprecation for details.
[        ] 1 error
[ +197 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':nearby_connections:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to
get full insights.
[   +4 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 18m 14s
[        ] 215 actionable tasks: 214 executed, 1 up-to-date
[+1552 ms] Running Gradle task 'assembleDebug'... (completed in 1096.6s)
[  +25 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 1,101,056ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[   +6 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

Looks like there is a problem with the `VERSION_CODES.Q` in nearby_connections package.

The following is my environment details from the command `flutter doctor --verbose`

```
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.2 at /home/apt/snap/flutter/common/flutter
    • Framework revision d79295af24 (3 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/apt/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 53.1.1
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • MYA L22 (mobile) • R9KBB17807153597 • android-arm64  • Android 6.0 (API
      23)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      91.0.4472.101

• No issues found!

```

Thank you in advance for your response, and also thanks for maintaining this project  👍

**Comment by mannprerak2** [comment]
Can you try running `flutter clean` and then try again?

**Comment by aptarmy** [comment]
Yes, I tried doing that.
```
$ flutter clean
Deleting build...                                                  10.9s
Deleting .dart_tool...                                              59ms
Deleting .packages...                                               16ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
```

After that I run `flutter pub get`, then `flutter run --verbose`, and then getting the same result, sir.

**Comment by mannprerak2** [comment]
Can you check your compileSdkVersion and targetSdkVersion. Make sure it is at 30.
See this https://github.com/mannprerak2/nearby_connections/blob/master/example/android/app/build.gradle#L28

**Comment by aptarmy** [comment]
Yes @mannprerak2, my `compileSdkVersion`, and `targetSdkVerison` is 30, and `minSdkVersion` is 21.
The installed `nearby_connections` version is 3.1.0.
This is a pretty strange bug, probably related to newly released flutter

After changing `compileSdkVerison` and `targetSdkVerison` to 30, I ran the command `flutter clean` and `flutter up get`, then `flutter run --verbose`.

But got the same result, sir.

**Comment by mannprerak2** [comment]
Can you try running the example app on your device?

**Comment by aptarmy** [comment]
@mannprerak2 thank you for your time, I really appreciate it. I run on my physical device every time, I don't use the emulator. Now I got this to work, my workaround is to downgrade `nearby_connections` from `v3.0.1` to `v2.0.2`. Now, there is no `if (VERSION.SDK_INT < VERSION_CODES.Q) {` error thing, and the app is built successfully, so I think it might be related to the new version of `nearby_connections`.

Again, thank you for your dedicated work in this project.

**Comment by mannprerak2** [comment]
@aptarmy I am unable to reproduce this error. (Using `Flutter 2.2.2 • channel stable`)

Also, version `2.0.2` will not work on Android 11 and above.

**Comment by mannprerak2** [comment]
Can you send me a minimal reproducible sample? You can send me the project you are working on but remove all the code you can while the error still persists. 

> I run on my physical device every time,

Also, this is a compile time error, so you don't need a device to test this. You can simply do - `flutter build apk`.

**Comment by aptarmy** [comment]
@mannprerak2 Thank you for your dedication.

> @aptarmy I am unable to reproduce this error. (Using `Flutter 2.2.2 • channel stable`)
> Also, version `2.0.2` will not work on Android 11 and above.
> Can you send me a minimal reproducible sample? You can send me the project you are working on but remove all the code you can while the error still persists.

Thank you for giving helps inspecting my code :) I tried downloading the example code provided in this repo, and everything works fine without any errors.
This made me to check my code, and there was something different than the example code provided.

Config in `pubspec.yaml` in my project

```
environment:
  sdk: ">=2.7.0 <3.0.0"
```

So I changed that `sdk` version to...

```
environment:
  sdk: ">=2.11.0 <3.0.0" # or sdk: ">=2.12.0<3.0.0" for null safety
```

It's working fine now with `nearby_connection v3.1.0`, `flutter (stable) v2.2.2`, and `compileSdkVersion: 30`. It was my mistake while upgrading the old version to the new one.
Thank you for your time, so I will close this issue now.

**Comment by JFtechOfficial** [comment]
Sorry, I'm having the exact same issue afte updating from v3.0.1. I'm picking up this project afte one month and I'm updating stuff. I'm on ```sdk: ">=2.12.0 <3.0.0"``` and I set ```targetSdkVersion```/```compileSdkVerison``` to 30. 

Here is the error:
```
Launching lib/main.dart on ONEPLUS A5010 in debug mode...
Running Gradle task 'assembleDebug'...
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/nearby_connections-3.1.0/android/src/main/java/com/pkmnapps/nearby_connections/NearbyConnectionsPlugin.java:448: error: cannot find symbol
                if (VERSION.SDK_INT < VERSION_CODES.Q) {
                                                   ^
  symbol:   variable Q
  location: class VERSION_CODES
Note: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/nearby_connections-3.1.0/android/src/main/java/com/pkmnapps/nearby_connections/NearbyConnectionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nearby_connections:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1
```

Here is the ```flutter doctor --verbose``` output (```flutter clean``` didn't have any effect):
```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.14.6 18G103 darwin-x64, locale it-IT)
    • Flutter version 2.2.2 at /Applications/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gianlucagalli/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/gianlucagalli/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ✗ Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • ONEPLUS A5010 (mobile) • 39a93283 • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```
Reverting to v3.0.1 fixes the issue

**Comment by mannprerak2** [comment]
Hi @JFtechOfficial, this is not really an issue with this package, so all I can recommend is to try running flutter clean and updating the dart sdk lower bound.

**Comment by SherwinJames** [comment]
Your compile version in your build.gradle for Android is set to "compileSdkVersion 28", causing compile errors:

```
C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nearby_connections-3.1.0\android\src\main\java\com\pkmnapps\nearby_connections\NearbyConnectionsPlugin.java:448: error: cannot find symbol
                if (VERSION.SDK_INT < VERSION_CODES.Q
```


Can you fix?
