### ISSUE TITLE
error when start Discovery in Android 13

### ISSUE THREAD

**Issue by punamz** [mannprerak2/nearby_connections#50]
In Android 13, when I call  `await Nearby().startDiscovery(...)` it throw an error below:

```
E/flutter (28009): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Failure, 8029: unknown status code: 8029, null, null)
E/flutter (28009): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (28009): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter (28009): <asynchronous suspension>
E/flutter (28009): #2      Nearby.startDiscovery (package:nearby_connections/src/nearby.dart:271:12)
E/flutter (28009): <asynchronous suspension>
```

**Comment by mannprerak2** [comment]
Hi, it turns out that Android 13 has added a new runtime permission which is now required for using Nearby Connections.

It's `NEARBY_WIFI_DEVICES`.

So you need to 
1. add it to your manifest
```XML
<uses-permission android:name="android.permission.NEARBY_WIFI_DEVICES" />
```

2. You will also need to ask this permission in runtime using some other package such as `permission_handler`

**Comment by punamz** [comment]
> 

thank you sir!, it's work for me
